<a href="https://colab.research.google.com/github/arathykrishnatr-creator/DS-Lab-Programs/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n = int(input("Enter size: "))
a = np.array(list(map(int, input("Enter first array: ").split())))
b = np.array(list(map(int, input("Enter second array: ").split())))
c = a * b
print("Result:", c)

Enter size: 3
Enter first array: 1 2 3
Enter second array: 4 5 6 
Result: [ 4 10 18]


In [ ]:
import numpy as np
n = int(input("Enter size: "))
a = np.array(list(map(int, input("Enter first array: ").split())))
b = np.array(list(map(int, input("Enter second array: ").split())))
print("Greater:", a > b)
print("Greater Equal:", a >= b)
print("Lesser:", a < b)

Enter size: 3
Enter first array: 1 2 3 
Enter second array: 4 5 6 
Greater: [False False False]
Greater Equal: [False False False]
Lesser: [ True  True  True]


In [ ]:
import numpy as np

a = np.arange(30, 71, 2)

print("Array:", a)

Array: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
import numpy as np
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
a = np.arange(0, 21)
print("Original Vector:", a)
a = -a
print("After Changing Sign:", a)

Original Vector: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After Changing Sign: [  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19 -20]


In [ ]:
import numpy as np

a = np.eye(5)

print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
n = int(input("Enter size: "))
a = np.array(list(map(int, input("Enter elements: ").split()))).reshape(n, n)
print("Array:\n", a)
print("Sum of all elements:", np.sum(a))
print("Row sum:", np.sum(a, axis=1))
print("Column sum:", np.sum(a, axis=0))

In [ ]:
import numpy as np

a = np.array(list(map(int, input("Enter array elements: ").split())))

np.savetxt("array.txt", a, fmt="%d")

b = np.loadtxt("array.txt", dtype=int)

print("Loaded Array:", b)

In [ ]:
import numpy as np

a = np.array(list(map(int, input("Enter first array: ").split())))
b = np.array(list(map(int, input("Enter second array: ").split())))

print(np.array_equal(a, b))

Enter first array: 2 4 6 8 
Enter second array: 1 2 3 4 
False


In [ ]:
import numpy as np

a = np.random.randint(1, 10, (4, 4))

print("Original Array:\n", a)

a[[0, 3]] = a[[3, 0]]

print("After Swapping:\n", a)

Original Array:
 [[9 6 5 8]
 [4 2 3 4]
 [3 8 9 7]
 [4 3 8 9]]
After Swapping:
 [[4 3 8 9]
 [4 2 3 4]
 [3 8 9 7]
 [9 6 5 8]]


In [ ]:
n = int(input("Enter the n: "))
k = int(input("Enter the k: "))
j = int(input("Enter the j: "))
m = int(input("Enter the m: "))
p = int(input("Enter the p: "))

if n <= 0 or k <= 0 or j <= 0 or m < 0 or p < 0:
    print("INVALID INPUT")
else:
    x = (m // k) + (p // j)

    if m % k != 0 or p % j != 0:
        x = x + 1

    if x > n:
        x = n

    n = n - x

    print("Number of Monkeys left on the tree:", n)


Enter the n: 20
Enter the k: 2
Enter the j: 3
Enter the m: 12
Enter the p: 12
Number of Monkeys left on the tree: 10
